---
name: Michael
surname: Bane
position: Experienced Analytics Professional
address: Melbourne, Australia
profilepic: profilepic.jpg
aboutme: An experienced Data Analyst and People Manager with deep knowledge of advanced concepts relating to Data Science and analytics. I am however primarily focused on applications, and love seeing data in action.
headcolor: 4a0aa3
phone: +61 439 639 100
email: baneanalytics@gmail.com
#twitter: baney64
github: michaelBane
linkedin: banemichael
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
#Default knitr options for the vitae template
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#Load packages
library(tibble)
library(vitae)
#Source data from separate file.
source('../resumeData.R')
```

# Work Experience

```{r workExperience}
workExperience %>%
  detailed_entries(
    what = company,
    where = glue::glue('{startDate} - {endDate}'),
    with = title,
    when = location,
    why = points)
```

# Core Skills

```{r}
skills %>%
  brief_entries(
    when = category,
    what = skills)
```

# Education

```{r eduation}
education %>%
  detailed_entries(
    what = institution,
    where = glue::glue('{startDate} - {endDate}'),
    with = degree,
    when = location,
    why = points)
```


